server:
  port: 8802

spring:
  application:
    name: cloud-stream-rabbit-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

    stream:
      # 在此处配置要绑定的rabbitmq的服务信息；
      binders:
        # 表示定义的名称, 用于于binding整合
        defaultRabbit:
          # 消息组件类型
          type: rabbit
          # 设置rabbitmq的相关的环境配置
          environment:
            spring:
              rabbitmq:
                host: localhost
                port: 5672
                username: guest
                password: guest
      # 服务的整合处理
      bindings:
        # 这个名字是一个通道的名称
        input:
          # 表示要使用的Exchange名称定义
          destination: studyExchange
          # 设置消息类型，本次为对象json，如果是文本则设置“text/plain”
          contentType: application/json
          # 设置要绑定的消息服务的具体设置
          binder: defaultRabbit




