server:
  port: 8001


spring:
  application:
    name: cloud-provider-hystrix-payment8001

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        # 注册空间地址
        namespace: 36df2268-32ce-4f11-95bc-e3d92a1e025e


      config:
        server-addr: 127.0.0.1:8848
        namespace: 36df2268-32ce-4f11-95bc-e3d92a1e025e
        ext-config:
            dataId: nacos-config-client-test.yaml
        group: DEFAULT_GROUP



